#!/usr/bin/env bash

# Generated by the `universalize-agents` skill. macOS/Linux only

# (see agent-setup.ps1 for Windows). Safe to re-run (idempotent)

# Project scope fills relative paths; global scope fills absolute paths

set -euo pipefail

AGENTS_DIR=".agents"

# LINK_MAP contract: one "SRC_SUBDIR|DEST_DIR" line per (platform x type)

# where SRC_SUBDIR is skills|agents|commands and DEST_DIR matches the scope

# (relative to repo root for project scope, absolute for global scope)

LINK_MAP="$(
 cat <<'EOF'
skills|.claude/skills
EOF
)"

log() { printf 'agent-setup: %s\n' "$1" >&2; }

# Relative paths (project scope) resolve from the repo root; this script lives

# at <root>/.agents/hooks/, so cd two levels up. Absolute paths are untouched

case "$AGENTS_DIR" in
 /*) ;;
 *) cd "$(dirname "$0")/../.." ;;
esac

# Echo the "../" prefix climbing from a relative dir back to the repo root

# so a symlink's target is correct relative to the link's own location

up_to_root() {
 up=""
 old_ifs="$IFS"
 IFS=/
 for _seg in $1; do up="../$up"; done
 IFS="$old_ifs"
 printf '%s' "$up"
}

link_item() {
 src="$1"
 dest="$2"

 if [ -L "$dest" ] && [ "$(readlink "$dest")" = "$src" ]; then
  return 0
 fi

# Refuse to replace a real (non-symlink) path that a user may own

 if [ -e "$dest" ] && [ ! -L "$dest" ]; then
  log "SKIP (real path in the way): $dest"
  return 0
 fi

 rm -f "$dest"
 ln -s "$src" "$dest"
}

printf '%s\n' "$LINK_MAP" | while IFS='|' read -r sub destdir; do
 [ -z "${sub:-}" ] && continue
 [ -z "${destdir:-}" ] && continue

 srcdir="$AGENTS_DIR/$sub"
 [ -d "$srcdir" ] || continue

 mkdir -p "$destdir"

# Clean up dangling symlinks in $destdir

 for link in "$destdir"/*; do
  [ -e "$link" ] || [ -L "$link" ] || continue
  if [ -L "$link" ] && [ ! -e "$link" ]; then
   log "removing broken symlink: $link"
   rm -f "$link"
  fi
 done

# Project scope only: keep the generated symlinks out of git via a single

# .gitignore per platform base dir (the dest's parent), listing each

# symlink subdir. The canonical content lives in (tracked) .agents/

 prefix=""
 case "$AGENTS_DIR" in
  /*) ;;
  *)
   prefix="$(up_to_root "$destdir")"
   gi="$(dirname "$destdir")/.gitignore"
   entry="$(basename "$destdir")/"
   if [ ! -f "$gi" ] || ! grep -qxF "$entry" "$gi"; then
    printf '%s\n' "$entry" >>"$gi"
   fi
   ;;
 esac

 for item in "$srcdir"/*; do
  [ -e "$item" ] || continue
  name="$(basename "$item")"
  link_item "${prefix}${srcdir}/${name}" "$destdir/$name"
 done
done

log "done."
